insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (1, 0, 'andRule', null, null);
    insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (11, 0, 'hasColorRule', null, 1);
           insert into PARAMETER_ENTITY (ID, RULE_ID, KEY, VALUE, TYPE) values (111, 11, 'color', 'black', 'java.lang.String');
           insert into PARAMETER_ENTITY (ID, RULE_ID, KEY, VALUE, TYPE) values (112, 11, 'a_key', 'a_value', 'java.lang.Integer');
           insert into PARAMETER_ENTITY (ID, RULE_ID, KEY, VALUE, TYPE) values (113, 11, 'b_key', 'b_value', 'java.lang.Integer');
           insert into PARAMETER_ENTITY (ID, RULE_ID, KEY, VALUE, TYPE) values (114, 11, 'c_key', 'c_value', 'java.lang.Integer');
    insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (12, 1, 'orRule', '', 1);
        insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (121, 0, 'onlyWeekendRule', '.', 12);
        insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (122, 1, 'priceGreaterThanRule', '.', 12);
        insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (123, 2, 'onlyWeekendRule', 'The product can only be propoced the weekend.', 12);
        insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (124, 3, 'priceGreaterThanRule', 'It''s necessary to have good profict.', 12);
                insert into PARAMETER_ENTITY (ID, RULE_ID, KEY, VALUE, TYPE) values (1221, 122, 'amount', '100.00', 'java.lang.Double');
insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (2, 0, 'notRule', null, null);
    insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (21, 0, 'onlyWeekendRule', null, 2);
insert into RULE_ENTITY (ID, INDEX, KEY, DESCRIPTION, PARENT_ID) values (3, 0, 'onlyWeekendRule', null, null);