= Spring Specification Reference Guide
Pinguet62 <https://github.com/pinguet62[GitHub]>
:revnumber: {project-version}
:toc: left
:toclevels: 3
:sectanchors:
:sectlinks:
:sectnums:

== Why this project?

=== Specification pattern

[quote, Wikipedia, https://en.wikipedia.org/wiki/Specification_pattern]
____
The *specification pattern* is a particular software design pattern, whereby *business rules* can be *recombined* by chaining the business rules together using boolean logic.
____

Concretely, instead to implement rules using `if`/`else` like with this code:
[source, java]
----
boolean canSellToMinor;
if (!product.isDangerous() && (product.getType().equals("toy") || product.getAmount() < 10))
    canSellToMinor = true;
----
the business rules are implemented *unitary* and *combined* to produce the final rule:
[source, java]
----
Rule isDangerous, isToy, amountLessThan10 = ...;
Rule combined = isDangerous.not().and( isToy.or(amountLessThan10) );
boolean canSellToMinor = combined.test(product);
----

=== Need of dynamism

The _specification pattern_ allow to produce readable and maintainable code.
But the final source code is *static*: you have to update/compile/deploy application to change business rules.

The goal of this project is to define to *manage* and *build* dynamically rules at runtime, without any modification into source code.

== General

=== Architecture

[ditaa]
----
              +=------------------------+
              |         +-----------+   |
              |         |{s}        |   |
              |         |@Repository|   |
              |         +-----------+   |
              |                         |
              |               ^         |
              |               |         |
              |               |         |
+------+    +-------+    +-----------+  |  +--------+    +-----+
|      |    |       |    |           |  |  | Admin  |    |Admin|
|Client|--->|Builder|--->|@Repository|<----|REST API|<---| UI  |
|      |    |       |    |           |  |  |        |    |     |
+------+    +-------+    +-----------+  |  +--------+    +-----+
              |                         |
              |                         |
              +=------------------------+
----

== Core API

The `Rule` interface is the base of specification pattern.

=== Simple usage

Definition:
[source, java]
----
class DangerousProductRule implements Rule<Product> {
    @Override
    public boolean test(Product param) {
        return param.isDangerous();
    }
}
----

Usage:
[source, java]
----
Rule rule = new DangerousProductRule();
Product product = new Product(...);
boolean isDangerousProduct = rule.test(product);
----

=== Composition

Example for this composition:
----
(NOT first) AND (second OR third)
----
based on these 3 *basic rules*:
[source, java]
----
Rule first = ...
Rule second = ...
Rule third = ...
----

==== Method chaining

`Rule` interface defines *default methods*, used for _method chaining_.

[source, java]
----
Rule composedRule = first.not().and( second.or(third) );
----

==== Composite pattern

`AndRule`/`OrRule`/`NotRule` are special `Rule` implementations, who work like *composite pattern* by accepting _variable length argument_ into constructor.

[source, java]
----
import fr.pinguet62.springruleengine.core.api.*;

Rule composedRule = new AndRule(
                        new NotRule(
                            first
                        ),
                        new OrRule(
                            second,
                            third
                        )
                    );
----

==== Utility methods

`and()`/`or()`/`not()` are *static* methods of `RuleUtils`.

[source, java]
----
import static fr.pinguet62.springruleengine.core.api.RuleUtils.*;

Rule composedRule = and(
                        not(
                            first
                        ),
                        or(
                            second,
                            third
                        )
                    );
----

=== Parameters

Create *minimal parameterized* rules, instead of _many specific_ rules.

Don't:
[source, java]
----
class ToyProductRule {}
class FoodProductRule {}
...
----

Do:
[source, java]
----
class TypeProductRule implements Rule<Product> {
    String type;

    TypeProductRule(String param) {
        this.color = param;
    }

    // ...
}

Rule toyProductRule = new TypeProductRule("toy");
Rule foodProductRule = new TypeProductRule("food");
...
----

== Builder

=== Key & Factory

All `Rule` are identified by unique **key**.

By default:

* the key is the `Class::getName()`;
* the factory use `BeanFactory::getBean()` to create an instance of rule.

TIP: Usually the component *scope* is `prototype`, to create distinct objects. +
It's possible to use other scope like `singleton`, but object must be _stateless_ and without parameter.

=== Composite rule

Sub-rules are *dynamically injected*.

==== Annotation & injection

Use `@RuleChild` or `@RuleChildren` on _field_ or _setter_ or _constructor argument_ to define the _injection point_ of sub-rules (used into database).

[source, java]
----
class ComposedRule<T> implements Rule<T> {
    @RuleChildren(
    List<Rule<T>> subRules;

    // ...
}
----
[source, java]
----
class ComposedRule<T> implements Rule<T> {
    List<Rule<T>> subRules;

    @RuleChildren
    void setType(List<Rule<T>> subRules) {
        this.subRules = subRules;
    };

    // ...
}
----
[source, java]
----
class ComposedRule<T> implements Rule<T> {
    final List<Rule<T>> subRules;

    ComposedRule(@RuleChildren List<Rule<T>> subRules) {
        this.subRules = subRules;
    };

    // ...
}
----

==== Behavior

The injection works like https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/annotation/Autowired.html[`@Autowired`] specification.
So injection support:

- conversion: `Collection`, `array`, _varargs_

=== Parameters

Parameters are *dynamically injected*.

==== Annotation & injection

Use `@RuleParameter()` on _field_ or _setter_ or _constructor argument_ to define the _injection point_ and the `key` of parameter (used into database).

[source, java]
----
class SampleRule implements Rule<T> {
    @RuleParameter("key")
    String param;

    // ...
}
----
[source, java]
----
class SampleRule implements Rule<T> {
    String param;

    @RuleParameter("key")
    void setType(String param) {
        this.param = param;
    };

    // ...
}
----
[source, java]
----
class SampleRule implements Rule<T> {
    final String param;

    SampleRule(@RuleParameter("key") String param) {
        this.param = param;
    };

    // ...
}
----

==== Behavior

The injection works like https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/annotation/Value.html[`@Value`] specification.
So injection support:

- conversion
- https://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#expressions[Spring Expression Language]

[source, java]
----
class SampleRule implements Rule<T> {
    @RuleParameter("rand")
    Integer param;

    // ...
}

TypeProductRule rule = ...;
// database parameter context = { "rand": "#{ T(java.lang.Math).ramdom() * 100 }" }
assertTrue(0 <= rule.param && rule.param <= 100);
----

=== Database

TODO

== Admin server

The admin application expose webservices (REST API) to manage rules.

Documentation: see `/swagger-ui.html` page.

== Admin UI

=== Spring Boot

The admin application can simply deployed using *Spring Boot & embedded Tomcat*.

1. Add _server_ and _client_ dependencies:

[source, xml]
.pom.xml
----
<dependency>
    <groupId>fr.pinguet62</groupId>
    <artifactId>spring-specification-admin-server</artifactId>
    <version>LATEST</version>
</dependency>
<dependency>
    <groupId>fr.pinguet62</groupId>
    <artifactId>spring-specification-admin-client</artifactId>
    <version>LATEST</version>
</dependency>
----

2. Enable _core_ & _server_ modules imporing `SpringSpecificationServerApplication` bean:

[source, java]
----
import fr.pinguet62.springruleengine.server.SpringSpecificationServerApplication;

@Import(SpringSpecificationServerApplication.class)
@SpringBootApplication
public class SampleApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootAdminApplication.class, args);
    }
}
----
