package fr.pinguet62.springruleengine.core.builder.database.autoconfigure;

/**
 * List of all {@link Bean} generated by Spring Specification.
 */
public class SpringSpecificationBeans {

    /**
     * @see org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
     */
    public static final String DATASOURCE_PROPERTIES = "springSpecification.dataSourceProperties";

    /**
     * @see javax.sql.DataSource
     */
    public static final String DATASOURCE = "springSpecification.dataSource";

    /**
     * @see javax.sql.XADataSource
     */
    public static final String XA_DATASOURCE = "springSpecification.xaDataSource";

    /**
     * @see org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer
     */
    public static final String DATASOURCE_INITIALIZER = "springSpecification.dataSourceInitializer";

    /**
     * @see org.springframework.boot.autoconfigure.orm.jpa.JpaProperties
     */
    public static final String JPA_PROPERTIES = "springSpecification.jpaProperties";

    /**
     * @see org.springframework.orm.jpa.JpaVendorAdapter
     */
    public static final String JPA_VENDOR_ADAPTER = "springSpecification.jpaVendorAdapter";

    /**
     * @see org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder
     */
    public static final String ENTITY_MANAGER_FACTORY_BUILDER = "springSpecification.entityManagerFactoryBuilder";

    /**
     * @see javax.persistence.EntityManagerFactory
     */
    public static final String ENTITY_MANAGER_FACTORY = "springSpecification.entityManagerFactory";

    /**
     * @see javax.transaction.TransactionManager
     */
    public static final String TRANSACTION_MANAGER = "springSpecification.transactionManager";

}
